-- DML seed/reference data scripts live here.
-- Keep runtime business data changes in application code, not seed scripts.

INSERT INTO end_points (url, method, roles, description, created_at, updated_at)
VALUES
    ('/api/v1/vendors/me', 'POST', '["ADMIN","VENDOR"]', '로그인한 화주 사용자의 사업 프로필을 생성합니다.', NOW(6), NOW(6)),
    ('/api/v1/vendors/me', 'GET', '["ADMIN","VENDOR"]', '로그인한 화주 사용자의 사업 프로필을 조회합니다.', NOW(6), NOW(6)),
    ('/api/v1/vendors/me', 'PUT', '["ADMIN","VENDOR"]', '로그인한 화주 사용자의 사업 프로필을 수정합니다.', NOW(6), NOW(6)),
    ('/api/v1/vendors/me/products', 'POST', '["ADMIN","VENDOR"]', '계약 요청과 단가 산정에 사용할 배송 품목 프로필을 생성합니다.', NOW(6), NOW(6)),
    ('/api/v1/vendors/me/products', 'GET', '["ADMIN","VENDOR"]', '로그인한 화주의 배송 품목 프로필 목록을 조회합니다.', NOW(6), NOW(6)),
    ('/api/v1/vendors/me/products/{productId}', 'PUT', '["ADMIN","VENDOR"]', '로그인한 화주의 배송 품목 프로필을 수정합니다.', NOW(6), NOW(6)),
    ('/api/v1/contract-requests', 'POST', '["ADMIN","VENDOR","AGENCY"]', '화주 또는 대리점이 상대방에게 계약 요청을 생성합니다.', NOW(6), NOW(6)),
    ('/api/v1/contract-requests', 'GET', '["ADMIN","VENDOR","AGENCY"]', '로그인한 사용자가 요청자로 생성한 계약 요청 목록을 조회합니다.', NOW(6), NOW(6)),
    ('/api/v1/contract-requests/received', 'GET', '["ADMIN","VENDOR","AGENCY"]', '로그인한 사용자가 승인자로 지정된 계약 요청 목록을 조회합니다.', NOW(6), NOW(6)),
    ('/api/v1/contract-requests/open', 'GET', '["ADMIN","AGENCY"]', '대리점이 제안할 수 있는 OPEN 상태 계약 요청 목록을 조회합니다.', NOW(6), NOW(6)),
    ('/api/v1/contract-requests/{contractRequestId}', 'GET', '["ADMIN","VENDOR","AGENCY"]', '로그인한 사용자가 참여자인 계약 요청 상세 정보를 조회합니다.', NOW(6), NOW(6)),
    ('/api/v1/contract-requests/{contractRequestId}', 'PUT', '["ADMIN","VENDOR","AGENCY"]', '로그인한 요청자가 계약 요청 정보를 수정합니다.', NOW(6), NOW(6)),
    ('/api/v1/contract-requests/{contractRequestId}/cancel', 'POST', '["ADMIN","VENDOR","AGENCY"]', '로그인한 요청자가 계약 요청을 취소합니다.', NOW(6), NOW(6)),
    ('/api/v1/contract-requests/{contractRequestId}/accept', 'POST', '["ADMIN","VENDOR","AGENCY"]', '승인자로 지정된 사용자가 계약 요청을 수락하고 최종 계약을 생성합니다.', NOW(6), NOW(6)),
    ('/api/v1/contract-requests/{contractRequestId}/reject', 'POST', '["ADMIN","VENDOR","AGENCY"]', '승인자로 지정된 사용자가 계약 요청을 거절합니다.', NOW(6), NOW(6)),
    ('/api/v1/contract-requests/{contractRequestId}/proposals', 'POST', '["ADMIN","AGENCY"]', '대리점이 계약 요청에 단가와 서비스 조건을 제안합니다.', NOW(6), NOW(6)),
    ('/api/v1/contract-requests/{contractRequestId}/proposals', 'GET', '["ADMIN","VENDOR"]', '화주가 자신의 계약 요청에 제출된 제안 목록을 조회합니다.', NOW(6), NOW(6)),
    ('/api/v1/proposals/me', 'GET', '["ADMIN","AGENCY"]', '로그인한 대리점의 제안 목록을 조회합니다.', NOW(6), NOW(6)),
    ('/api/v1/proposals/{proposalId}', 'PUT', '["ADMIN","AGENCY"]', '대리점이 자신이 제출한 제안의 단가와 조건을 수정합니다.', NOW(6), NOW(6)),
    ('/api/v1/proposals/{proposalId}/withdraw', 'POST', '["ADMIN","AGENCY"]', '대리점이 자신이 제출한 제안을 철회합니다.', NOW(6), NOW(6)),
    ('/api/v1/proposals/{proposalId}/accept', 'POST', '["ADMIN","VENDOR"]', '화주가 대리점 제안을 선택해 최종 계약을 생성합니다.', NOW(6), NOW(6)),
    ('/api/v1/proposals/{proposalId}/negotiations', 'GET', '["ADMIN","VENDOR","AGENCY"]', '화주 또는 대리점이 제안의 가격 조율 이벤트 목록을 조회합니다.', NOW(6), NOW(6)),
    ('/api/v1/proposals/{proposalId}/negotiations/price-offers', 'POST', '["ADMIN","VENDOR","AGENCY"]', '화주 또는 대리점이 제안 단가 조율 이벤트를 등록합니다.', NOW(6), NOW(6)),
    ('/api/v1/proposals/{proposalId}/negotiations/{eventId}/accept', 'POST', '["ADMIN","VENDOR","AGENCY"]', '상대방이 제안한 가격 조율 이벤트를 수락합니다.', NOW(6), NOW(6)),
    ('/api/v1/proposals/{proposalId}/negotiations/{eventId}/reject', 'POST', '["ADMIN","VENDOR","AGENCY"]', '상대방이 제안한 가격 조율 이벤트를 거절합니다.', NOW(6), NOW(6)),
    ('/api/v1/contracts/vendor/me', 'GET', '["ADMIN","VENDOR"]', '로그인한 화주의 최종 계약 목록을 조회합니다.', NOW(6), NOW(6)),
    ('/api/v1/contracts/agency/me', 'GET', '["ADMIN","AGENCY"]', '로그인한 대리점의 최종 계약 목록을 조회합니다.', NOW(6), NOW(6)),
    ('/api/v1/agencies', 'GET', '["PUBLIC"]', '화주는 계약 요청 대상 대리점을 조회하고, 배송기사는 회원가입 또는 프로필 등록 시 소속 대리점을 검색합니다.', NOW(6), NOW(6)),
    ('/api/v1/agencies/{agencyId}', 'GET', '["PUBLIC"]', '화주와 배송기사가 대리점 대표자명, 연락처, 주소, 서비스 조건 등 상세 정보를 조회합니다.', NOW(6), NOW(6)),
    ('/api/v1/agencies/me', 'POST', '["ADMIN","AGENCY"]', '로그인한 대리점 사용자의 영업 거점 프로필을 생성합니다.', NOW(6), NOW(6)),
    ('/api/v1/agencies/me', 'GET', '["ADMIN","AGENCY"]', '로그인한 대리점 사용자의 영업 거점 프로필을 조회합니다.', NOW(6), NOW(6)),
    ('/api/v1/agencies/me', 'PUT', '["ADMIN","AGENCY"]', '로그인한 대리점 사용자의 영업 거점 프로필을 수정합니다.', NOW(6), NOW(6)),
    ('/api/v1/delivers/me', 'POST', '["ADMIN","DRIVER"]', '로그인한 배송기사 사용자의 프로필을 생성합니다.', NOW(6), NOW(6)),
    ('/api/v1/delivers/me', 'GET', '["ADMIN","DRIVER"]', '로그인한 배송기사 사용자의 프로필을 조회합니다.', NOW(6), NOW(6)),
    ('/api/v1/delivers/me', 'PUT', '["ADMIN","DRIVER"]', '로그인한 배송기사 사용자의 프로필을 수정합니다.', NOW(6), NOW(6)),
    ('/api/v1/delivers/agency/me', 'GET', '["ADMIN","AGENCY"]', '로그인한 대리점에 소속된 배송기사 목록을 조회합니다.', NOW(6), NOW(6)),
    ('/api/v1/delivers/freelancers', 'GET', '["ADMIN","AGENCY"]', '대리점이 계약 요청할 수 있는 프리랜서 배송기사 목록을 조회합니다.', NOW(6), NOW(6)),
    ('/api/v1/deliver-contracts', 'POST', '["ADMIN","AGENCY"]', '대리점이 소속 배송기사에게 담당 지역과 단가 조건을 제안합니다.', NOW(6), NOW(6)),
    ('/api/v1/deliver-contracts/agency/me', 'GET', '["ADMIN","AGENCY"]', '로그인한 대리점이 생성한 배송기사 계약 목록을 조회합니다.', NOW(6), NOW(6)),
    ('/api/v1/deliver-contracts/driver/me', 'GET', '["ADMIN","DRIVER"]', '로그인한 배송기사가 자신에게 요청된 계약 목록을 조회합니다.', NOW(6), NOW(6)),
    ('/api/v1/deliver-contracts/{deliverContractId}', 'PUT', '["ADMIN","AGENCY"]', '대리점이 요청 상태의 배송기사 계약 조건을 수정합니다.', NOW(6), NOW(6)),
    ('/api/v1/deliver-contracts/{deliverContractId}/accept', 'POST', '["ADMIN","DRIVER"]', '배송기사가 자신에게 요청된 배송기사 계약을 수락합니다.', NOW(6), NOW(6)),
    ('/api/v1/deliver-contracts/{deliverContractId}/reject', 'POST', '["ADMIN","DRIVER"]', '배송기사가 자신에게 요청된 배송기사 계약을 거절합니다.', NOW(6), NOW(6)),
    ('/api/v1/deliver-contracts/{deliverContractId}/cancel', 'POST', '["ADMIN","AGENCY"]', '대리점이 요청 상태의 배송기사 계약을 취소합니다.', NOW(6), NOW(6)),
    ('/api/v1/driver-works', 'POST', '["ADMIN","AGENCY"]', '대리점이 최종 계약 물량에 대한 기사 일감을 생성합니다.', NOW(6), NOW(6)),
    ('/api/v1/driver-works/agency/me', 'GET', '["ADMIN","AGENCY"]', '로그인한 대리점이 생성한 기사 일감 목록을 조회합니다.', NOW(6), NOW(6)),
    ('/api/v1/driver-works/driver/me/open', 'GET', '["ADMIN","DRIVER"]', '로그인한 소속 배송기사가 신청 가능한 OPEN 일감 목록을 조회합니다.', NOW(6), NOW(6)),
    ('/api/v1/driver-works/driver/me/assigned', 'GET', '["ADMIN","DRIVER"]', '로그인한 배송기사에게 확정 할당된 기사 일감 목록을 조회합니다.', NOW(6), NOW(6)),
    ('/api/v1/driver-works/driver/me/applications', 'GET', '["ADMIN","DRIVER"]', '로그인한 배송기사가 신청한 기사 일감 신청 목록을 조회합니다.', NOW(6), NOW(6)),
    ('/api/v1/driver-works/{driverWorkId}/applications', 'GET', '["ADMIN","AGENCY"]', '대리점이 특정 기사 일감의 신청자 목록을 조회합니다.', NOW(6), NOW(6)),
    ('/api/v1/driver-works/{driverWorkId}/applications', 'POST', '["ADMIN","DRIVER"]', '소속 배송기사가 OPEN 상태 기사 일감에 신청합니다.', NOW(6), NOW(6)),
    ('/api/v1/driver-works/{driverWorkId}/applications/me', 'DELETE', '["ADMIN","DRIVER"]', '소속 배송기사가 OPEN 상태 일감에 대한 신청을 철회합니다.', NOW(6), NOW(6)),
    ('/api/v1/driver-works/{driverWorkId}/applications/{applicationId}/select', 'POST', '["ADMIN","AGENCY"]', '대리점이 신청자 중 한 명을 선택해 기사 일감을 확정합니다.', NOW(6), NOW(6)),
    ('/api/v1/driver-works/{driverWorkId}/assign', 'POST', '["ADMIN","AGENCY"]', '대리점이 OPEN 상태 기사 일감을 소속 배송기사에게 직접 할당합니다.', NOW(6), NOW(6)),
    ('/api/v1/driver-works/{driverWorkId}/cancel', 'POST', '["ADMIN","AGENCY"]', '대리점이 완료 전 기사 일감을 취소합니다.', NOW(6), NOW(6)),
    ('/api/v1/driver-works/{driverWorkId}/complete', 'POST', '["ADMIN","AGENCY"]', '대리점이 할당된 기사 일감을 완료 처리합니다.', NOW(6), NOW(6)),
    ('/api/v1/notifications/me', 'GET', '["ADMIN","VENDOR","AGENCY","DRIVER"]', '로그인한 사용자의 최근 30일 알림 목록을 조회합니다.', NOW(6), NOW(6)),
    ('/api/v1/notifications/stream', 'GET', '["ADMIN","VENDOR","AGENCY","DRIVER"]', '로그인한 사용자의 새 알림을 SSE 스트림으로 구독합니다.', NOW(6), NOW(6)),
    ('/api/v1/notifications/me/unread-count', 'GET', '["ADMIN","VENDOR","AGENCY","DRIVER"]', '로그인한 사용자의 최근 30일 미확인 알림 수를 조회합니다.', NOW(6), NOW(6)),
    ('/api/v1/notifications/{notificationId}/read', 'PUT', '["ADMIN","VENDOR","AGENCY","DRIVER"]', '로그인한 사용자의 특정 알림을 읽음 처리합니다.', NOW(6), NOW(6)),
    ('/api/v1/notifications/me/read-all', 'PUT', '["ADMIN","VENDOR","AGENCY","DRIVER"]', '로그인한 사용자의 읽지 않은 알림을 모두 읽음 처리합니다.', NOW(6), NOW(6))
ON DUPLICATE KEY UPDATE
    roles = VALUES(roles),
    description = VALUES(description),
    updated_at = VALUES(updated_at);
