CREATE TABLE IF NOT EXISTS contract_requests (
    id BINARY(16) NOT NULL COMMENT '계약 요청 식별자',
    type VARCHAR(30) NOT NULL COMMENT '계약 요청 유형',
    requester_type VARCHAR(30) NOT NULL COMMENT '요청자 유형',
    requester_id BINARY(16) NOT NULL COMMENT '요청자 식별자',
    approver_type VARCHAR(30) NOT NULL COMMENT '승인자 유형',
    approver_id BINARY(16) NULL COMMENT '승인자 식별자',
    product_id BINARY(16) NULL COMMENT '대표 배송 품목 템플릿 식별자',
    pickup_region VARCHAR(100) NOT NULL COMMENT '집하 지역',
    pickup_address VARCHAR(255) NULL COMMENT '집하 주소',
    contract_type VARCHAR(30) NOT NULL DEFAULT 'SINGLE' COMMENT '계약 유형',
    pickup_date_from DATE NULL COMMENT '집하 희망 시작일',
    pickup_date_to DATE NULL COMMENT '집하 희망 종료일',
    delivery_date_from DATE NULL COMMENT '배송 희망 시작일',
    delivery_date_to DATE NULL COMMENT '배송 희망 종료일',
    recurring_pickup_cycle VARCHAR(30) NULL COMMENT '정기 집하 주기',
    recurring_pickup_days_of_week VARCHAR(100) NULL COMMENT '정기 집하 요일 목록',
    recurring_pickup_day_of_month INT NULL COMMENT '정기 집하 월 기준 일자',
    monthly_volume INT NOT NULL COMMENT '월 예상 물량',
    product_category VARCHAR(30) NOT NULL COMMENT '대표 품목 카테고리',
    product_name VARCHAR(100) NOT NULL COMMENT '대표 품목명',
    box_size VARCHAR(30) NOT NULL COMMENT '대표 박스 규격',
    pickup_start_time VARCHAR(10) NOT NULL COMMENT '집하 가능 시작 시간',
    pickup_end_time VARCHAR(10) NOT NULL COMMENT '집하 가능 종료 시간',
    saturday_delivery_required BOOLEAN NOT NULL COMMENT '토요일 배송 필요 여부',
    return_required BOOLEAN NOT NULL COMMENT '반품 처리 필요 여부',
    cold_chain_type VARCHAR(30) NOT NULL COMMENT '대표 콜드체인 유형',
    target_unit_price DECIMAL(15, 2) NULL COMMENT '희망 박스당 단가',
    memo VARCHAR(255) NULL COMMENT '계약 요청 메모',
    status VARCHAR(30) NOT NULL COMMENT '계약 요청 상태',
    created_at DATETIME(6) NOT NULL COMMENT '생성 시각',
    updated_at DATETIME(6) NOT NULL COMMENT '마지막 수정 시각',
    PRIMARY KEY (id),
    KEY idx_contract_requests_requester (requester_type, requester_id),
    KEY idx_contract_requests_approver (approver_type, approver_id),
    KEY idx_contract_requests_product_id (product_id),
    KEY idx_contract_requests_status (status),
    KEY idx_contract_requests_open_agency (type, status, approver_type, approver_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='계약 요청';

CREATE TABLE IF NOT EXISTS contract_request_items (
    id BINARY(16) NOT NULL COMMENT '계약 요청 품목 식별자',
    contract_request_id BINARY(16) NOT NULL COMMENT '계약 요청 식별자',
    product_id BINARY(16) NULL COMMENT '배송 품목 템플릿 식별자',
    product_category VARCHAR(30) NOT NULL COMMENT '품목 카테고리',
    product_name VARCHAR(100) NOT NULL COMMENT '품목명',
    box_size VARCHAR(30) NOT NULL COMMENT '박스 규격',
    box_quantity INT NOT NULL COMMENT '박스 수량',
    item_quantity INT NOT NULL COMMENT '상품 수량',
    average_weight_gram INT NULL COMMENT '평균 무게(g)',
    fragile BOOLEAN NOT NULL COMMENT '파손 주의 여부',
    liquid BOOLEAN NOT NULL COMMENT '액체 포함 여부',
    fresh_food BOOLEAN NOT NULL COMMENT '신선식품 여부',
    cold_chain_type VARCHAR(30) NOT NULL COMMENT '콜드체인 유형',
    target_unit_price DECIMAL(15, 2) NULL COMMENT '희망 박스당 단가',
    created_at DATETIME(6) NOT NULL COMMENT '생성 시각',
    updated_at DATETIME(6) NOT NULL COMMENT '마지막 수정 시각',
    PRIMARY KEY (id),
    KEY idx_contract_request_items_request_id (contract_request_id),
    KEY idx_contract_request_items_product_id (product_id),
    KEY idx_contract_request_items_cold_chain (cold_chain_type),
    KEY idx_contract_request_items_box_size (box_size)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='계약 요청 품목';

CREATE TABLE IF NOT EXISTS proposals (
    id BINARY(16) NOT NULL COMMENT '제안 식별자',
    contract_request_id BINARY(16) NOT NULL COMMENT '계약 요청 식별자',
    vendor_id BINARY(16) NOT NULL COMMENT '화주 식별자',
    agency_id BINARY(16) NOT NULL COMMENT '대리점 식별자',
    unit_price DECIMAL(15, 2) NOT NULL COMMENT '대표 박스당 제안 단가',
    initial_unit_price DECIMAL(15, 2) NOT NULL COMMENT '최초 대표 제안 단가',
    final_unit_price DECIMAL(15, 2) NULL COMMENT '최종 대표 협의 단가',
    pending_negotiation_id BINARY(16) NULL COMMENT '응답 대기 중인 협의 이벤트 식별자',
    next_sequence BIGINT NOT NULL DEFAULT 1 COMMENT '다음 협의 이벤트 순번',
    pickup_start_time VARCHAR(10) NOT NULL COMMENT '집하 가능 시작 시간',
    pickup_end_time VARCHAR(10) NOT NULL COMMENT '집하 가능 종료 시간',
    saturday_delivery_available BOOLEAN NOT NULL COMMENT '토요일 배송 가능 여부',
    return_available BOOLEAN NOT NULL COMMENT '반품 처리 가능 여부',
    cold_chain_type VARCHAR(30) NOT NULL COMMENT '지원 콜드체인 유형',
    memo VARCHAR(255) NULL COMMENT '제안 메모',
    status VARCHAR(30) NOT NULL COMMENT '제안 상태',
    created_at DATETIME(6) NOT NULL COMMENT '생성 시각',
    updated_at DATETIME(6) NOT NULL COMMENT '마지막 수정 시각',
    PRIMARY KEY (id),
    UNIQUE KEY uk_proposals_contract_request_agency (contract_request_id, agency_id),
    KEY idx_proposals_contract_request_id (contract_request_id),
    KEY idx_proposals_vendor_id (vendor_id),
    KEY idx_proposals_agency_id (agency_id),
    KEY idx_proposals_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='대리점 제안';

CREATE TABLE IF NOT EXISTS proposal_negotiation_events (
    id BINARY(16) NOT NULL COMMENT '제안 협의 이벤트 식별자',
    proposal_id BINARY(16) NOT NULL COMMENT '제안 식별자',
    sequence BIGINT NOT NULL COMMENT '제안 내 협의 이벤트 순번',
    actor_type VARCHAR(30) NOT NULL COMMENT '협의 이벤트 작성자 유형',
    event_type VARCHAR(30) NOT NULL COMMENT '협의 이벤트 유형',
    unit_price DECIMAL(15, 2) NULL COMMENT '대표 협의 단가',
    memo VARCHAR(255) NULL COMMENT '협의 메모',
    status VARCHAR(30) NOT NULL COMMENT '협의 이벤트 상태',
    created_at DATETIME(6) NOT NULL COMMENT '생성 시각',
    updated_at DATETIME(6) NOT NULL COMMENT '마지막 수정 시각',
    PRIMARY KEY (id),
    UNIQUE KEY uk_proposal_negotiation_events_proposal_sequence (proposal_id, sequence),
    KEY idx_proposal_negotiation_events_proposal_id (proposal_id),
    KEY idx_proposal_negotiation_events_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='제안 협의 이벤트';

CREATE TABLE IF NOT EXISTS proposal_negotiation_event_items (
    id BINARY(16) NOT NULL COMMENT '제안 협의 품목 단가 식별자',
    proposal_negotiation_event_id BINARY(16) NOT NULL COMMENT '제안 협의 이벤트 식별자',
    contract_request_item_id BINARY(16) NOT NULL COMMENT '계약 요청 품목 식별자',
    unit_price DECIMAL(15, 2) NOT NULL COMMENT '품목별 협의 단가',
    created_at DATETIME(6) NOT NULL COMMENT '생성 시각',
    updated_at DATETIME(6) NOT NULL COMMENT '마지막 수정 시각',
    PRIMARY KEY (id),
    UNIQUE KEY uk_proposal_negotiation_event_items_event_request_item (
        proposal_negotiation_event_id,
        contract_request_item_id
    ),
    KEY idx_proposal_negotiation_event_items_event_id (proposal_negotiation_event_id),
    KEY idx_proposal_negotiation_event_items_request_item_id (contract_request_item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='제안 협의 품목 단가';

CREATE TABLE IF NOT EXISTS proposal_items (
    id BINARY(16) NOT NULL COMMENT '제안 품목 단가 식별자',
    proposal_id BINARY(16) NOT NULL COMMENT '제안 식별자',
    contract_request_item_id BINARY(16) NOT NULL COMMENT '계약 요청 품목 식별자',
    unit_price DECIMAL(15, 2) NOT NULL COMMENT '품목별 제안 단가',
    created_at DATETIME(6) NOT NULL COMMENT '생성 시각',
    updated_at DATETIME(6) NOT NULL COMMENT '마지막 수정 시각',
    PRIMARY KEY (id),
    UNIQUE KEY uk_proposal_items_proposal_request_item (proposal_id, contract_request_item_id),
    KEY idx_proposal_items_proposal_id (proposal_id),
    KEY idx_proposal_items_contract_request_item_id (contract_request_item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='제안 품목 단가';

CREATE TABLE IF NOT EXISTS contracts (
    id BINARY(16) NOT NULL COMMENT '최종 계약 식별자',
    contract_request_id BINARY(16) NOT NULL COMMENT '계약 요청 식별자',
    proposal_id BINARY(16) NOT NULL COMMENT '채택된 제안 식별자',
    vendor_id BINARY(16) NOT NULL COMMENT '화주 식별자',
    agency_id BINARY(16) NOT NULL COMMENT '대리점 식별자',
    pickup_region VARCHAR(100) NOT NULL COMMENT '확정 집하 지역',
    pickup_address VARCHAR(255) NULL COMMENT '확정 집하 주소',
    contract_type VARCHAR(30) NOT NULL DEFAULT 'SINGLE' COMMENT '계약 유형',
    pickup_date_from DATE NULL COMMENT '확정 집하 시작일',
    pickup_date_to DATE NULL COMMENT '확정 집하 종료일',
    delivery_date_from DATE NULL COMMENT '확정 배송 시작일',
    delivery_date_to DATE NULL COMMENT '확정 배송 종료일',
    recurring_pickup_cycle VARCHAR(30) NULL COMMENT '정기 집하 주기',
    recurring_pickup_days_of_week VARCHAR(100) NULL COMMENT '정기 집하 요일 목록',
    recurring_pickup_day_of_month INT NULL COMMENT '정기 집하 월 기준 일자',
    monthly_volume INT NOT NULL COMMENT '확정 월 예상 물량',
    product_category VARCHAR(30) NOT NULL COMMENT '대표 품목 카테고리',
    product_name VARCHAR(100) NOT NULL COMMENT '대표 품목명',
    box_size VARCHAR(30) NOT NULL COMMENT '대표 박스 규격',
    unit_price DECIMAL(15, 2) NOT NULL COMMENT '대표 확정 단가',
    pickup_start_time VARCHAR(10) NOT NULL COMMENT '확정 집하 시작 시간',
    pickup_end_time VARCHAR(10) NOT NULL COMMENT '확정 집하 종료 시간',
    saturday_delivery_available BOOLEAN NOT NULL COMMENT '토요일 배송 가능 여부',
    return_available BOOLEAN NOT NULL COMMENT '반품 처리 가능 여부',
    cold_chain_type VARCHAR(30) NOT NULL COMMENT '확정 콜드체인 유형',
    memo VARCHAR(255) NULL COMMENT '최종 계약 메모',
    status VARCHAR(30) NOT NULL COMMENT '최종 계약 상태',
    created_at DATETIME(6) NOT NULL COMMENT '생성 시각',
    updated_at DATETIME(6) NOT NULL COMMENT '마지막 수정 시각',
    PRIMARY KEY (id),
    UNIQUE KEY uk_contracts_contract_request_id (contract_request_id),
    UNIQUE KEY uk_contracts_proposal_id (proposal_id),
    KEY idx_contracts_vendor_id (vendor_id),
    KEY idx_contracts_agency_id (agency_id),
    KEY idx_contracts_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='최종 계약';

CREATE TABLE IF NOT EXISTS contract_items (
    id BINARY(16) NOT NULL COMMENT '최종 계약 품목 식별자',
    contract_id BINARY(16) NOT NULL COMMENT '최종 계약 식별자',
    product_id BINARY(16) NULL COMMENT '배송 품목 템플릿 식별자',
    product_category VARCHAR(30) NOT NULL COMMENT '품목 카테고리',
    product_name VARCHAR(100) NOT NULL COMMENT '품목명',
    box_size VARCHAR(30) NOT NULL COMMENT '박스 규격',
    box_quantity INT NOT NULL COMMENT '박스 수량',
    item_quantity INT NOT NULL COMMENT '상품 수량',
    average_weight_gram INT NULL COMMENT '평균 무게(g)',
    fragile BOOLEAN NOT NULL COMMENT '파손 주의 여부',
    liquid BOOLEAN NOT NULL COMMENT '액체 포함 여부',
    fresh_food BOOLEAN NOT NULL COMMENT '신선식품 여부',
    cold_chain_type VARCHAR(30) NOT NULL COMMENT '콜드체인 유형',
    unit_price DECIMAL(15, 2) NOT NULL COMMENT '확정 품목 단가',
    created_at DATETIME(6) NOT NULL COMMENT '생성 시각',
    updated_at DATETIME(6) NOT NULL COMMENT '마지막 수정 시각',
    PRIMARY KEY (id),
    KEY idx_contract_items_contract_id (contract_id),
    KEY idx_contract_items_product_id (product_id),
    KEY idx_contract_items_cold_chain (cold_chain_type),
    KEY idx_contract_items_box_size (box_size)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='최종 계약 품목';
