CREATE TABLE IF NOT EXISTS users (
    id BINARY(16) NOT NULL,
    login_id VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    encoded_password VARCHAR(255) NOT NULL,
    name VARCHAR(50) NOT NULL,
    role VARCHAR(30) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    deleted_at DATETIME(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_users_login_id (login_id),
    UNIQUE KEY uk_users_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS end_points (
    id BIGINT NOT NULL AUTO_INCREMENT,
    url VARCHAR(255) NOT NULL,
    method VARCHAR(10) NOT NULL,
    roles JSON NOT NULL,
    description VARCHAR(255) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_end_points_url_method (url, method)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS account_recovery_tokens (
    id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    purpose VARCHAR(30) NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at DATETIME(6) NOT NULL,
    used_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_account_recovery_tokens_token_hash (token_hash),
    KEY idx_account_recovery_tokens_user_purpose (user_id, purpose),
    KEY idx_account_recovery_tokens_expires_at (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vendors (
    id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    business_name VARCHAR(100) NOT NULL,
    business_registration_number VARCHAR(30) NULL,
    representative_name VARCHAR(50) NOT NULL,
    phone_number VARCHAR(30) NOT NULL,
    postal_code VARCHAR(20) NULL,
    address VARCHAR(255) NOT NULL,
    address_detail VARCHAR(255) NULL,
    main_region VARCHAR(100) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    deleted_at DATETIME(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_vendors_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS products (
    id BINARY(16) NOT NULL,
    vendor_id BINARY(16) NOT NULL,
    category VARCHAR(30) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255) NULL,
    average_price DECIMAL(15, 2) NULL,
    average_weight_gram INT NULL,
    box_size VARCHAR(30) NULL,
    box_quantity INT NOT NULL,
    item_quantity INT NOT NULL,
    destination_postal_code VARCHAR(20) NULL,
    destination_address VARCHAR(255) NOT NULL,
    destination_address_detail VARCHAR(255) NULL,
    fragile BOOLEAN NOT NULL,
    liquid BOOLEAN NOT NULL,
    fresh_food BOOLEAN NOT NULL,
    cold_chain_type VARCHAR(30) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    deleted_at DATETIME(6) NULL,
    PRIMARY KEY (id),
    KEY idx_products_vendor_id (vendor_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS contract_requests (
    id BINARY(16) NOT NULL,
    type VARCHAR(30) NOT NULL,
    requester_type VARCHAR(30) NOT NULL,
    requester_id BINARY(16) NOT NULL,
    approver_type VARCHAR(30) NOT NULL,
    approver_id BINARY(16) NULL,
    product_id BINARY(16) NULL,
    pickup_region VARCHAR(100) NOT NULL,
    pickup_address VARCHAR(255) NULL,
    monthly_volume INT NOT NULL,
    product_category VARCHAR(30) NOT NULL,
    product_name VARCHAR(100) NOT NULL,
    box_size VARCHAR(30) NOT NULL,
    pickup_start_time VARCHAR(10) NOT NULL,
    pickup_end_time VARCHAR(10) NOT NULL,
    saturday_delivery_required BOOLEAN NOT NULL,
    return_required BOOLEAN NOT NULL,
    cold_chain_type VARCHAR(30) NOT NULL,
    target_unit_price DECIMAL(15, 2) NULL,
    memo VARCHAR(255) NULL,
    status VARCHAR(30) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_contract_requests_requester (requester_type, requester_id),
    KEY idx_contract_requests_approver (approver_type, approver_id),
    KEY idx_contract_requests_product_id (product_id),
    KEY idx_contract_requests_status (status),
    KEY idx_contract_requests_open_agency (type, status, approver_type, approver_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS contract_request_items (
    id BINARY(16) NOT NULL,
    contract_request_id BINARY(16) NOT NULL,
    product_id BINARY(16) NULL,
    product_category VARCHAR(30) NOT NULL,
    product_name VARCHAR(100) NOT NULL,
    box_size VARCHAR(30) NOT NULL,
    box_quantity INT NOT NULL,
    item_quantity INT NOT NULL,
    average_weight_gram INT NULL,
    fragile BOOLEAN NOT NULL,
    liquid BOOLEAN NOT NULL,
    fresh_food BOOLEAN NOT NULL,
    cold_chain_type VARCHAR(30) NOT NULL,
    target_unit_price DECIMAL(15, 2) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_contract_request_items_request_id (contract_request_id),
    KEY idx_contract_request_items_product_id (product_id),
    KEY idx_contract_request_items_cold_chain (cold_chain_type),
    KEY idx_contract_request_items_box_size (box_size)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS proposals (
    id BINARY(16) NOT NULL,
    contract_request_id BINARY(16) NOT NULL,
    vendor_id BINARY(16) NOT NULL,
    agency_id BINARY(16) NOT NULL,
    unit_price DECIMAL(15, 2) NOT NULL,
    initial_unit_price DECIMAL(15, 2) NOT NULL,
    final_unit_price DECIMAL(15, 2) NULL,
    pending_negotiation_id BINARY(16) NULL,
    next_sequence BIGINT NOT NULL DEFAULT 1,
    pickup_start_time VARCHAR(10) NOT NULL,
    pickup_end_time VARCHAR(10) NOT NULL,
    saturday_delivery_available BOOLEAN NOT NULL,
    return_available BOOLEAN NOT NULL,
    cold_chain_type VARCHAR(30) NOT NULL,
    memo VARCHAR(255) NULL,
    status VARCHAR(30) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_proposals_contract_request_agency (contract_request_id, agency_id),
    KEY idx_proposals_contract_request_id (contract_request_id),
    KEY idx_proposals_vendor_id (vendor_id),
    KEY idx_proposals_agency_id (agency_id),
    KEY idx_proposals_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS proposal_negotiation_events (
    id BINARY(16) NOT NULL,
    proposal_id BINARY(16) NOT NULL,
    sequence BIGINT NOT NULL,
    actor_type VARCHAR(30) NOT NULL,
    event_type VARCHAR(30) NOT NULL,
    unit_price DECIMAL(15, 2) NULL,
    memo VARCHAR(255) NULL,
    status VARCHAR(30) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_proposal_negotiation_events_proposal_sequence (proposal_id, sequence),
    KEY idx_proposal_negotiation_events_proposal_id (proposal_id),
    KEY idx_proposal_negotiation_events_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS proposal_negotiation_event_items (
    id BINARY(16) NOT NULL,
    proposal_negotiation_event_id BINARY(16) NOT NULL,
    contract_request_item_id BINARY(16) NOT NULL,
    unit_price DECIMAL(15, 2) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_proposal_negotiation_event_items_event_request_item (
        proposal_negotiation_event_id,
        contract_request_item_id
    ),
    KEY idx_proposal_negotiation_event_items_event_id (proposal_negotiation_event_id),
    KEY idx_proposal_negotiation_event_items_request_item_id (contract_request_item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS proposal_items (
    id BINARY(16) NOT NULL,
    proposal_id BINARY(16) NOT NULL,
    contract_request_item_id BINARY(16) NOT NULL,
    unit_price DECIMAL(15, 2) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_proposal_items_proposal_request_item (proposal_id, contract_request_item_id),
    KEY idx_proposal_items_proposal_id (proposal_id),
    KEY idx_proposal_items_contract_request_item_id (contract_request_item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS contracts (
    id BINARY(16) NOT NULL,
    contract_request_id BINARY(16) NOT NULL,
    proposal_id BINARY(16) NOT NULL,
    vendor_id BINARY(16) NOT NULL,
    agency_id BINARY(16) NOT NULL,
    pickup_region VARCHAR(100) NOT NULL,
    pickup_address VARCHAR(255) NULL,
    monthly_volume INT NOT NULL,
    product_category VARCHAR(30) NOT NULL,
    product_name VARCHAR(100) NOT NULL,
    box_size VARCHAR(30) NOT NULL,
    unit_price DECIMAL(15, 2) NOT NULL,
    pickup_start_time VARCHAR(10) NOT NULL,
    pickup_end_time VARCHAR(10) NOT NULL,
    saturday_delivery_available BOOLEAN NOT NULL,
    return_available BOOLEAN NOT NULL,
    cold_chain_type VARCHAR(30) NOT NULL,
    memo VARCHAR(255) NULL,
    status VARCHAR(30) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_contracts_contract_request_id (contract_request_id),
    UNIQUE KEY uk_contracts_proposal_id (proposal_id),
    KEY idx_contracts_vendor_id (vendor_id),
    KEY idx_contracts_agency_id (agency_id),
    KEY idx_contracts_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS contract_items (
    id BINARY(16) NOT NULL,
    contract_id BINARY(16) NOT NULL,
    product_id BINARY(16) NULL,
    product_category VARCHAR(30) NOT NULL,
    product_name VARCHAR(100) NOT NULL,
    box_size VARCHAR(30) NOT NULL,
    box_quantity INT NOT NULL,
    item_quantity INT NOT NULL,
    average_weight_gram INT NULL,
    fragile BOOLEAN NOT NULL,
    liquid BOOLEAN NOT NULL,
    fresh_food BOOLEAN NOT NULL,
    cold_chain_type VARCHAR(30) NOT NULL,
    unit_price DECIMAL(15, 2) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_contract_items_contract_id (contract_id),
    KEY idx_contract_items_product_id (product_id),
    KEY idx_contract_items_cold_chain (cold_chain_type),
    KEY idx_contract_items_box_size (box_size)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agencies (
    id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    carrier VARCHAR(30) NOT NULL,
    agency_name VARCHAR(100) NOT NULL,
    business_registration_number VARCHAR(30) NULL,
    representative_name VARCHAR(50) NOT NULL,
    phone_number VARCHAR(30) NOT NULL,
    postal_code VARCHAR(20) NULL,
    address VARCHAR(255) NOT NULL,
    address_detail VARCHAR(255) NULL,
    main_region VARCHAR(100) NOT NULL,
    service_regions VARCHAR(500) NOT NULL,
    weekday_pickup_start_time VARCHAR(10) NULL,
    weekday_pickup_end_time VARCHAR(10) NULL,
    saturday_pickup_available BOOLEAN NOT NULL,
    saturday_delivery_available BOOLEAN NOT NULL,
    return_available BOOLEAN NOT NULL,
    supported_cold_chain_types JSON NOT NULL,
    max_monthly_volume INT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    deleted_at DATETIME(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_agencies_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS delivers (
    id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    agency_id BINARY(16) NOT NULL,
    driver_name VARCHAR(50) NOT NULL,
    phone_number VARCHAR(30) NOT NULL,
    vehicle_number VARCHAR(30) NULL,
    service_regions VARCHAR(500) NOT NULL,
    active BOOLEAN NOT NULL,
    memo VARCHAR(255) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    deleted_at DATETIME(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_delivers_user_id (user_id),
    KEY idx_delivers_agency_id (agency_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS deliver_contracts (
    id BINARY(16) NOT NULL,
    agency_id BINARY(16) NOT NULL,
    deliver_id BINARY(16) NOT NULL,
    service_region VARCHAR(100) NOT NULL,
    expected_monthly_volume INT NOT NULL,
    unit_price DECIMAL(15, 2) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NULL,
    memo VARCHAR(255) NULL,
    status VARCHAR(30) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_deliver_contracts_agency_id (agency_id),
    KEY idx_deliver_contracts_deliver_id (deliver_id),
    KEY idx_deliver_contracts_agency_deliver_status (agency_id, deliver_id, status),
    KEY idx_deliver_contracts_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS notifications (
    id BINARY(16) NOT NULL,
    receiver_user_id BINARY(16) NOT NULL,
    sender_user_id BINARY(16) NULL,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(100) NOT NULL,
    message VARCHAR(500) NOT NULL,
    link_url VARCHAR(255) NULL,
    reference_type VARCHAR(50) NULL,
    reference_id BINARY(16) NULL,
    read_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_notifications_receiver_created_at (receiver_user_id, created_at),
    KEY idx_notifications_receiver_read_at_created_at (receiver_user_id, read_at, created_at),
    KEY idx_notifications_reference (reference_type, reference_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
